service: server
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-localstack
custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    host: http://localhost:4566/
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: ping
          method: get